### ISSUE TITLE
Credentials are being logged in plain text

### ISSUE THREAD

**Issue by danlugo92** [shocknet/api#119]
![photo_2020-07-18_17-51-02](https://user-images.githubusercontent.com/32064271/87862542-4f4f7d00-c91f-11ea-9624-4305ccf3e360.jpg)

**Comment by danlugo92** [comment]
RSA Keys too but I don't know if that's dangerous.

**Comment by capitalistdog** [comment]
https://github.com/shocknet/api/commit/714688be2ac3336dcea469acb0e84c1559490745
