### ISSUE TITLE
Only GET requests should have hash cache mechanics

### ISSUE THREAD

**Issue by danlugo92** [shocknet/api#82]
POSTs don't exhibit this issue. Guessing they are exempted from caching somehow but couldn't find that code.
 
Every other request (yes,exactly  every other) either PUT/DELETE returns `304` as the status code, empty body.

The only hit for `304` is in the cache handling code.

So it's a caching thing.

I wasn't getting it in the HTTP client because I do not send any cache related headers I guess.

Only GET requests should implement caching.

**Comment by Emad-salah** [comment]
This issue is fixed in ae0576c73ec34cb8bc176a8bd93861c5946199b3
