### ISSUE TITLE
Make cache headers mandatory

### ISSUE THREAD

**Issue by danlugo92** [shocknet/api#83]
A client NOT sending a cache header (because a front-end programmer) can result in unnecessary data being transmitted. This can then result in hard-to-trace high data usage.

If cache headers are mandatory for all applicable GET endpoints then we avoid this issue.

Found this out when dealing with #82

Add an environment variable to disable this behavior (default behaviour should be REQUIRED cache headers) for easier debugging through HTTP clients e.g. Postman.

**Comment by Emad-salah** [comment]
This issue is fixed in ae0576c73ec34cb8bc176a8bd93861c5946199b3
